version: "3"

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - webserver1
      - webserver2
  
  webserver1:
    build: ./bin/webserver
    container_name: webserver1 
    volumes:
      - ./www:/var/www/html/

  webserver2:
    build: ./bin/webserver
    container_name: webserver2 
    volumes:
      - ./www:/var/www/html/

  mysql-master:
    build: ./bin/mysql
    container_name: 'png-mysql-test-master'
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql_master:/var/lib/mysql
      - ./logs/mysql_master:/var/log/mysql
      - ./data/initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: wlstjd12
      MYSQL_DATABASE: test_db
      MYSQL_USER: 'replica_user'
      MYSQL_PASSWORD: 'replica_password'
      MYSQL_HOST: '%'
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=test_db --default-authentication-plugin=mysql_native_password

  mysql-slave:
    build: ./bin/mysql
    container_name: 'png-mysql-test-slave'
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql_slave:/var/lib/mysql
      - ./logs/mysql_slave:/var/log/mysql
      - ./data/initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: wlstjd12
      MYSQL_DATABASE: test_db
      MYSQL_USER: 'replica_user'
      MYSQL_PASSWORD: 'replica_password'
      
    depends_on:
      - mysql-master
    command: --server-id=2 --relay-log=relay-bin --log-slave-updates=1 --binlog-do-db=test_db --default-authentication-plugin=mysql_native_password

  # ==================================
  # 모니터링 Exporter 서비스 추가
  # ==================================

  # 1. MySQL 지표 수집 (복제 상태, 쿼리 등)
    # 1. MySQL 마스터 익스포터
  mysql_exporter_master:
    image: prom/mysqld-exporter:latest
    container_name: mysql_exporter_master
    ports:
      - "9104:9104"
    command:
      - "--mysqld.username=exporter:replica_password"
      - "--mysqld.address=mysql:3306"

    depends_on:
      - mysql-master
    restart: unless-stopped

  # 2. MySQL 슬레이브 익스포터
  mysql_exporter_slave:
    image: prom/mysqld-exporter:latest
    container_name: mysql_exporter_slave
    ports:
      - "9105:9105"
    command:
      - "--mysqld.username=exporter:replica_password"
      - "--mysqld.address=mysql:3307"
    depends_on:
      - mysql-slave
    restart: unless-stopped

  # 2. 시스템 지표 수집 (CPU, 메모리, 디스크 등)
  # 호스트 OS의 지표를 수집합니다.
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    ports:
      - "9100:9100"
    volumes:
      - /:/host:ro,rslave
    restart: unless-stopped
 
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    # Exporter가 먼저 시작되도록 의존성 추가
    depends_on:
      - mysql_exporter_master
      - mysql_exporter_slave
      - node_exporter
    
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus