version: "3"

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - webserver1
      - webserver2
  
  webserver1:
    build: ./bin/webserver
    container_name: webserver1  
    volumes:
      - ./www:/var/www/html/

  webserver2:
    build: ./bin/webserver
    container_name: webserver2  
    volumes:
      - ./www:/var/www/html/

  mysql-master:
    build: ./bin/mysql
    container_name: 'png-mysql-test-master'
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql_master:/var/lib/mysql
      - ./logs/mysql_master:/var/log/mysql
      - ./data/initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: wlstjd12
      MYSQL_DATABASE: test_db
      MYSQL_USER: 'replica_user'
      MYSQL_PASSWORD: 'replica_password'
      MYSQL_HOST: '%'
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=test_db

  mysql-slave:
    build: ./bin/mysql
    container_name: 'png-mysql-test-slave'
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql_slave:/var/lib/mysql
      - ./logs/mysql_slave:/var/log/mysql
      - ./data/initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: wlstjd12
      MYSQL_DATABASE: test_db
      MYSQL_USER: 'replica_user'
      MYSQL_PASSWORD: 'replica_password'
      
    depends_on:
      - mysql-master
    command: --server-id=2 --relay-log=relay-bin --log-slave-updates=1 --binlog-do-db=test_db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 100M
    depends_on:
      - mysql-master
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus